#### Numpy with python

In [ ]:
# import package
# Numpy- a package in python that provides multidimensional array object
import numpy as np
# numpy array has fix size 
# if we change size of numpy array after its creation 
# then new array in created and old one gets deleted 
# datatypes in numpy array must be same 
#

In [5]:
 import numpy as np
a=np.arange(15).reshape(3,5)
a
# numpy array of 15 itemns , rehsape(row, column) row=3, column =5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
# shape
print("shape of array: ",a.shape)
print("dimension of array: ",a.ndim)  # 2 dimensional array 
print("size of array: ",a.size)
print("itemsize of array: ",a.itemsize)# itemsize- size of datatype of each elements in array

shape of array:  (3, 5)
dimension of array:  2
size of array:  15
itemsize of array:  4


In [17]:
a.data  # buffer containing actual data

In [25]:
# array creation 
import numpy as np
a=np.array([3,2,6,1])
a
print("size :  ",a.size)
print("dtype :  ",a.dtype)
print("itemsize :  ",a.itemsize)
print("shape :  ",a.shape)
# ndarray hasn't dimension attribute

size :   4
dtype :   int32
itemsize :   4
shape :   (4,)


In [29]:
# 2-d array
b=np.array([(1,5,4),(6,5,8)])
b
# must be homogenous , i.e no. of element for x, y must be equal
# can't create non-homogeneous array

array([[1, 5, 4],
       [6, 5, 8]])

In [31]:
# explicitly specifying dtype of array
c=np.array([[1,2],[5,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [5.+0.j, 4.+0.j]])

In [37]:
# creatine arrays of zeroes and ones 
# zeroes method create array full of zeroes
# ones method create array  full of ones 
print("array of zeros: ")
np.zeros((3,5))

array of zeros: 


array of ones 


array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
print("array of ones ")
np.ones((2,3))

array of ones 


array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# array of empty
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
# arange create array into given range
# start, end, steps
np.arange(10,30,5)

array([10, 15, 20, 25])

In [47]:
# arange also accepts float arguments
np.arange(1,3,0.5)

array([1. , 1.5, 2. , 2.5])

In [10]:
import numpy as np
a=np.array([10,20,30,40])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [12]:
c=a-b
c

array([10, 19, 28, 37])

In [14]:
b**2  # all the operation will be applied to all elements

array([0, 1, 4, 9])

In [16]:
10*np.sin(a)

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [18]:
a<35

array([ True,  True,  True, False])

In [26]:
A=np.arange(2,4,0.5)
B=np.arange(5,7,0.5)

In [28]:
A*B

array([10.  , 13.75, 18.  , 22.75])

In [30]:
rg=np.random.default_rng(1)  # create instance of default  random no. generator
a=np.ones((2,3),dtype=int)
b=rg.random((2,3))
a*=3
a
# a+=b this can't be done , b won't automaticaally convert to a's dtype

array([[3, 3, 3],
       [3, 3, 3]])

In [32]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [34]:
a

array([[3, 3, 3],
       [3, 3, 3]])

#### Reverse array 

In [37]:
arr=np.array([1,6,5,3,8])
reverse_arr=np.flip(arr)
print("reversed array is:  ",reverse_arr)

reversed array is:   [8 3 5 6 1]


In [39]:
# reverse 2-d array
arr_2d=np.array([[1,5,7,3,4],[2,5,4,8,2],[1,7,6,3,9]])
arr_2d

array([[1, 5, 7, 3, 4],
       [2, 5, 4, 8, 2],
       [1, 7, 6, 3, 9]])

In [41]:
re_arr=np.flip(arr_2d)
print("reversed array:  ",re_arr)
# if axis is not specified for flip , 
# both column-wise and row-wise arr will reverse

reversed array:   [[9 3 6 7 1]
 [2 8 4 5 2]
 [4 3 7 5 1]]


In [43]:
# reverse through row
re_row=np.flip(re_arr,axis=0)
print(re_row)
# elements reversed only row wise 

[[4 3 7 5 1]
 [2 8 4 5 2]
 [9 3 6 7 1]]


In [47]:
# reverse through column
re_col=np.flip(re_arr,axis=1)
print(re_col)

[[1 7 6 3 9]
 [2 5 4 8 2]
 [1 5 7 3 4]]


In [49]:
# reverse using any index 
arr_i=np.flip(arr_2d[:,1])
print(arr_i)

[7 5 5]


In [2]:
# reshape and flatten multi-dimensional array
import numpy as np
x=np.array([[1,5,6],[3,6,5],[2,5,6]])
x

array([[1, 5, 6],
       [3, 6, 5],
       [2, 5, 6]])

In [3]:
x.shape

(3, 3)

In [4]:
#flatten the multidimension array
#using .flatten- the changes made to new array won't affect 
# the parent original array
#using .ravel method-new array created in this method is refernce to parent array #
#(i.e a view a created) and the changes made to new array affect the parent array #
#efficient method- .ravel- cuz it doesn't create any copy , memory efficient
x.flatten()

array([1, 5, 6, 3, 6, 5, 2, 5, 6])

In [5]:
x.ravel()

array([1, 5, 6, 3, 6, 5, 2, 5, 6])

In [6]:
max?
#? - to access all the useful info about any function,variable
#function or about any element we want to access##

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [8]:
x?

Type:        ndarray
String form:
[[1 5 6]
 [3 6 5]
 [2 5 6]]
Length:      3
File:        c:\users\asus\anaconda3\anaconda_setup\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-ty

In [9]:
def double(a):
    return a*2

In [10]:
double?
# created a function and accesssing info about it

Signature: double(a)
Docstring: <no docstring>
File:      c:\users\asus\appdata\local\temp\ipykernel_14524\2157672883.py
Type:      function

In [13]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
a=np.array([1,5,6,9,0,5,0])
b=np.array([6,4,9,1,3,5,0])

plt.subplot([a,b])


ValueError: Single argument to subplot must be a three-digit integer, not [array([1, 5, 6, 9, 0, 5, 0]), array([6, 4, 9, 1, 3, 5, 0])]

<Figure size 640x480 with 0 Axes>

### Mutation,replication of array

In [19]:
a=np.array([2,6,9,7])
print("original array")
print(a)
b=a[:2]
b+=1
print("array after changes made")
print(a)
print("array->b")
print(b)

original array
[2 6 9 7]
array after changes made
[3 7 9 7]
array->b
[3 7]


In [22]:
# joining 4   (2 by 2) arrays into big 4x4 array
# using block method
A=np.ones((2,2))
B=np.ones((2,2))
C=np.zeros((2,2))
D=np.diag((1,2))
np.block([[A,B],[C,D]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 2.]])

In [25]:
# brief summary
A=np.ones((2,2))
A

array([[1., 1.],
       [1., 1.]])

In [27]:
B=np.eye(2,2)
B
# eye- returns 1 at diagonal and 0 at  other places

array([[1., 0.],
       [0., 1.]])

In [29]:
# another eye example
K=np.eye(4,5)
K

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [31]:
C=np.zeros((2,2))
C

array([[0., 0.],
       [0., 0.]])

In [32]:
D=np.diag((-3,-4))
D

array([[-3,  0],
       [ 0, -4]])